DROP  TABLE  IF EXISTS  `#__routes`;

CREATE TABLE  IF NOT EXISTS  `#__routes` (
  `id` int(11) NOT  NULL  AUTO_INCREMENT,
  `language` char(7) NOT NULL,
  `published` tinyint(4) DEFAULT NULL,
  `title` VARCHAR(55) NOT NULL,
  `start_point_name` VARCHAR(55) NOT NULL,
  `finish_point_name` VARCHAR(55) NOT NULL,
  `apikey` VARCHAR(50) NOT NULL,
  `start_point` VARCHAR(55) NOT NULL,
  `finish_point` VARCHAR(55) NOT NULL,
  `speed` VARCHAR(10) NOT NULL,
  `intermediate_point1` VARCHAR(50) NOT NULL,
  `intermediate_point2` VARCHAR(50) NOT NULL,
  `intermediate_point3` VARCHAR(50) NOT NULL,
  `intermediate_point4` VARCHAR(50) NOT NULL,
  `intermediate_point5` VARCHAR(50) NOT NULL,
  `intermediate_point6` VARCHAR(50) NOT NULL,
  `intermediate_point7` VARCHAR(50) NOT NULL,
  `intermediate_point8` VARCHAR(50) NOT NULL,
  `interval` VARCHAR(25) NOT NULL,
  `days` VARCHAR(25) NOT NULL,
  `time` VARCHAR(25) NOT NULL,
  `description` text NOT  NULL,
  `backgound_color` tinyint(4) DEFAULT NULL,
  `but_tickets` tinyint(4) DEFAULT NULL,
  `but_memorandum` tinyint(4) DEFAULT NULL,
  `memorandum_desc` text NOT  NULL,
  `published_table` tinyint(4) DEFAULT NULL,
  `timetable` VARCHAR(4096) NOT NULL,
  `note` VARCHAR(1024) NOT NULL,
  `phone_dispatcher1` VARCHAR(25) NOT NULL,
  `phone_dispatcher2` VARCHAR(25) NOT NULL,
  `phone_dispatcher3` VARCHAR(25) NOT NULL,
  `phone_dispatcher4` VARCHAR(25) NOT NULL,
  `phone_dispatcher5` VARCHAR(25) NOT NULL,
  `phone_dispatcher6` VARCHAR(25) NOT NULL,
  `phone_dispatcher7` VARCHAR(25) NOT NULL,
  `phone_dispatcher8` VARCHAR(25) NOT NULL,
  `published_img` tinyint(4) DEFAULT NULL,
  `img_start` varchar(1024) NOT NULL DEFAULT '',
  `img_start_title` varchar(50) NOT NULL,
  `img_start_desc` varchar(1024) NOT NULL,
  `img_finish` varchar(1024) NOT NULL DEFAULT '',
  `img_finish_title` varchar(50) NOT NULL,
  `img_finish_desc` varchar(1024) NOT NULL,
  `img_route` varchar(1024) NOT NULL DEFAULT '',
  `img_route_title` varchar(50) NOT NULL,
  `img_route_desc` varchar(1024) NOT NULL,
  `published_slider` tinyint(4) DEFAULT NULL,
  `published_additionally` tinyint(4) DEFAULT NULL,
  `text_additionally` text NOT  NULL,
  `alias` varchar(45) DEFAULT NULL,
  `buses` varchar(1024) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;